### ISSUE TITLE
dcp_inspect doesn't report InterOp DCPs with 25 FPS

### ISSUE THREAD

**Issue by 4lm** [wolfgangw/backports#34]
If an InterOp DCP has 25 FPS dcp_inspect doesn't output an error or at least an hint message. Although the InterOp specs only allow 24 (2K, 4K, 3D2K) or 48 FPS (2K).

**Comment by wolfgangw** [comment]
Done (3bd5a7f3361d40f91dd9eecef60026607f0a432d), only took 10 years :)
