### ISSUE TITLE
JPEG2000 bitrate

### ISSUE THREAD

**Issue by liloneum** [wolfgangw/backports#50]
Nice to have:

Analyse average and max bitrate (e.g. asdcp-info -r).
Error (or hint?) if bitrate exceeding 250 Mb/s

**Comment by wolfgangw** [comment]
Done. See 1f8782345e87d7dbb42805a8b2df094dce122491 (Weighted mean reported in composition summary).

**Comment by wolfgangw** [comment]
Also note that the reported bitrates are taken from the complete assets respectively -- instead of frames ```entry``` to ```entry + duration```.

I think it is good enough, though. Cases where the bigger part of an asset (with wildly different bitrate) would go unused should be rare. Agree?

**Comment by liloneum** [comment]
Yes it's quite enough! This issue was minor.
