### ISSUE TITLE
Whitespace inside DCSubtitle Id element

### ISSUE THREAD

**Issue by matmat** [wolfgangw/backports#56]
dcp_inspect gives five errors:

Error: AM c54c93a4-9ff6-4c8e-9a6c-56fd779198a5: Asset UUID: Not a UUID: /dcp/GFF2015-INGEST/HORSE-MONEY/d3d2b53b-b02d-4b69-8840-aa05de8c53fd/ING_R3.xml:  d3d2b53b-b02d-4b69-8840-aa05de8c53fd

Error: AM c54c93a4-9ff6-4c8e-9a6c-56fd779198a5: UUID mismatch: /dcp/GFF2015-INGEST/HORSE-MONEY/d3d2b53b-b02d-4b69-8840-aa05de8c53fd/ING_R3.xml: Listed: d3d2b53b-b02d-4b69-8840-aa05de8c53fd Asset:  d3d2b53b-b02d-4b69-8840-aa05de8c53fd 

Error: DCSubtitle 67422d7a-0acb-42fa-b51d-47db40e4d94a: Schema check: DCSubtitle.v1.mattsson.xsd /dcp/GFF2015-INGEST/HORSE-MONEY/67422d7a-0acb-42fa-b51d-47db40e4d94a/ING_R2.xml line 3: Element 'SubtitleID': ' 67422d7a-0acb-42fa-b51d-47db40e4d94a ' is not a valid value of the atomic type 'UUIDType'.

Error: DCSubtitle d3d2b53b-b02d-4b69-8840-aa05de8c53fd: Schema check: DCSubtitle.v1.mattsson.xsd /dcp/GFF2015-INGEST/HORSE-MONEY/d3d2b53b-b02d-4b69-8840-aa05de8c53fd/ING_R3.xml line 3: Element 'SubtitleID': [facet 'pattern'] The value ' d3d2b53b-b02d-4b69-8840-aa05de8c53fd ' is not accepted by the pattern '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'.

Error: DCSubtitle d3d2b53b-b02d-4b69-8840-aa05de8c53fd: Schema check: DCSubtitle.v1.mattsson.xsd /dcp/GFF2015-INGEST/HORSE-MONEY/d3d2b53b-b02d-4b69-8840-aa05de8c53fd/ING_R3.xml line 3: Element 'SubtitleID': ' d3d2b53b-b02d-4b69-8840-aa05de8c53fd ' is not a valid value of the atomic type 'UUIDType'.

[note that the github markup processing eats the leading and trailing spaces in the first two error messages above]

Excerpt from DCSubtitle file:

`
<?xml version="1.0" encoding="UTF-8"?>
<DCSubtitle Version="1.0">
  <SubtitleID> d3d2b53b-b02d-4b69-8840-aa05de8c53fd </SubtitleID>
`

I am going to test if this causes problems while playing back on a real server/projector tomorrow. But this DCP has played at som major festivals (TIFF for instance) so I doubt it.

**Comment by matmat** [comment]
Also note that there is leading and trailing whitespace in TI:s example of SubtitleId usage on page 11 in the spec: http://www.dlp.com/downloads/pdf_dlp_cinema_cinecanvas_rev_c.pdf

**Comment by matmat** [comment]
Tested in the field on a Dolby DSS200 + Barcko DP2K-20C. Subtitles rendered without problems.

**Comment by wolfgangw** [comment]
Done. See b1ef869761ddfea307cb94eec658455b67d8fffa.
