### ISSUE TITLE
asdcplib_version NoMethodError

### ISSUE THREAD

**Issue by kieranjol** [wolfgangw/backports#71]
Hi,

I'm on Ubuntu 16.04. 
I installed dcp_inspect via the setup script. All went well but it said that the asdcplib stuff wasn't installed.
I downloaded the source code of asdcp-lib 2.7.19 and ran ./configure, make, and sudo make install (i had to run sudo as I was getting errors otherwise).

When I run dcp_inspect, I get the following error:
```
~/asdcplib-2.7.19$ dcp_inspect
 NoMethodError: undefined method `map' for nil:NilClass
 /home/testo/.digital_cinema_tools/.bin/dcp_inspect:398:in `asdcplib_version'
 /home/testo/.digital_cinema_tools/.bin/dcp_inspect:4738:in `<main>'
 
 Sorry, dcp_inspect v1.2017.07.11 crashed
 Please get in touch to help fix it
 See https://github.com/wolfgangw
 Your feedback is much appreciated. Thanks in advance
 

```

Not sure what else to provide, but here's what happens when I run asdcp-util

```
asdcp-util
asdcp-util: error while loading shared libraries: libasdcp-2.7.19.so: cannot open shared object file: No such file or directory
```

**Comment by wha0077** [comment]
I am having the exact same issue. I am trying to set up a new system and unable to install this on either Ubuntu or Fedora, any version. All the errors are related to asdcplib. Any ideas?

**Comment by wolfgangw** [comment]
@kieranjol hi, sorry for the late reply.

Your manual ```asdcplib``` installation was incomplete/broken. Also, at the time there may have been bugs wrt ```asdcplib``` installation in ```digital-cinema-tools-setup```.

If you're still around: give it another try.
