### ISSUE TITLE
install script doesn't work anymore

### ISSUE THREAD

**Issue by pguarri** [wolfgangw/backports#72]
Install script doesn't work anymore on ubuntu 14.0.5

**Comment by kieranjol** [comment]
I'd imagine that sharing the complete terminal output with error message would help in resolving this?

**Comment by pguarri** [comment]
Of course:

There were errors:
Error: openjpeg: Failed to download tarball. Try again later
Error: Failed to extract tarball at /home/pier/.digital_cinema_tools/.lib/openjpeg
