### ISSUE TITLE
Timecode Range error

### ISSUE THREAD

**Issue by liloneum** [wolfgangw/backports#81]
New strange behaviour with some EasyDCP Creator content:

Traceback (most recent call last):
	21: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:4865:in `<main>'
	20: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:4617:in `dcp_inspect'
	19: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:4617:in `each_with_index'
	18: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:4617:in `each'
	17: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:4618:in `block in dcp_inspect'
	16: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:4618:in `each'
	15: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:4625:in `block (2 levels) in dcp_inspect'
	14: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:2839:in `cpl_inspect_xml'
	13: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:2839:in `each_with_index'
	12: from /home/lejolimai/.digital_cinema_tools/.lib/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.4/lib/nokogiri/xml/node_set.rb:203:in `each'
	11: from /home/lejolimai/.digital_cinema_tools/.lib/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.4/lib/nokogiri/xml/node_set.rb:203:in `upto'
	10: from /home/lejolimai/.digital_cinema_tools/.lib/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.4/lib/nokogiri/xml/node_set.rb:204:in `block in each'
	 9: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:2859:in `block in cpl_inspect_xml'
	 8: from /home/lejolimai/.digital_cinema_tools/.lib/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.4/lib/nokogiri/xml/node_set.rb:203:in `each'
	 7: from /home/lejolimai/.digital_cinema_tools/.lib/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.4/lib/nokogiri/xml/node_set.rb:203:in `upto'
	 6: from /home/lejolimai/.digital_cinema_tools/.lib/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.4/lib/nokogiri/xml/node_set.rb:204:in `block in each'
	 5: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:3217:in `block (2 levels) in cpl_inspect_xml'
	 4: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:962:in `new'
	 3: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:962:in `new'
	 2: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:950:in `initialize'
	 1: from /home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:1267:in `validate!'
/home/lejolimai/.digital_cinema_tools/.bin/dcp_inspect:1033:in `validate_atoms!': There can be no more than 999 hours, got 23860 (Timecode::RangeError)

**Comment by overlookmotel** [comment]
Does this DCP have soft subtitles by any chance? Could be same problem as https://github.com/wolfgangw/backports/issues/79
I came across a DCP today exhibiting same issue as in #79.

**Comment by liloneum** [comment]
Indeed!
